# Generated by Django 4.2.2 on 2023-06-24 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hub",
            old_name="lat",
            new_name="address_lat",
        ),
        migrations.RenameField(
            model_name="hub",
            old_name="lon",
            new_name="address_lon",
        ),
        migrations.RemoveField(
            model_name="order",
            name="address",
        ),
        migrations.AddField(
            model_name="hub",
            name="address_string",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="address_lat",
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="address_lon",
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="address_string",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orderhistory",
            name="timestamp",
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.DeleteModel(
            name="Address",
        ),
    ]
