# Generated by Django 4.2.2 on 2023-06-24 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_lat_hub_address_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waybill',
            name='route_url',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HubWorkHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.hub')),
            ],
        ),
    ]
