# Generated by Django 4.2.2 on 2023-06-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_order_customer_name_order_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='telegram_id',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
