# Generated by Django 4.2.2 on 2023-06-24 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_courier_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='hub',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='web.hub'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courier',
            name='telegram_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
