# Generated by Django 4.2.2 on 2023-06-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_courier_hub_alter_courier_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('appointed', 'Appointed'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courier',
            name='status',
            field=models.CharField(choices=[('free', 'Free'), ('busy', 'Busy')], max_length=255),
        ),
    ]
