# Generated by Django 4.2.2 on 2023-06-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0007_alter_hub_address_string_alter_hub_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hubworkhours",
            name="hub",
        ),
        migrations.RenameField(
            model_name="waybillorder",
            old_name="number",
            new_name="order_number",
        ),
        migrations.AddField(
            model_name="orderhistory",
            name="value",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="waybill",
            name="route_url",
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name="CourierWorkHours",
        ),
        migrations.DeleteModel(
            name="HubWorkHours",
        ),
    ]
