# Generated by Django 4.2.2 on 2023-06-25 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0008_remove_hubworkhours_hub_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hub",
            name="logo",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="waybillorder",
            name="waybill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="orders",
                to="web.waybill",
            ),
        ),
    ]
