# Generated by Django 4.2.2 on 2023-06-25 11:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0009_hub_logo_alter_waybillorder_waybill"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="hub",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.RESTRICT, to="web.hub"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orderhistory",
            name="event",
            field=models.CharField(
                choices=[("status_changed", "Status Changed")], max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="orderhistory",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
