# Generated by Django 4.2.2 on 2023-06-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0011_waybill_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
